### ISSUE TITLE
Android App Crash  when device Register call 

### ISSUE THREAD

**Issue by mayurloved** [Pushwoosh/pushwoosh-phonegap-plugin#153]
Hello,

When I run app and try to register device even call app crashed with below log.
I have all the SDK and Library Are Upto Date.

FATAL EXCEPTION: IntentService[GCMRegistrationService]
                                                               Process: com.tinfo.app, PID: 27571
                                                               java.lang.NoSuchMethodError: android.support.v4.content.ContextCompat.getNoBackupFilesDir
                                                                   at com.google.android.gms.iid.zzd.zzeb(Unknown Source)
                                                                   at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                                   at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                                   at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
                                                                   at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
                                                                   at com.pushwoosh.GCMRegistrationService.register(Unknown Source)
                                                                   at com.pushwoosh.GCMRegistrationService.onHandleIntent(Unknown Source)
                                                                   at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:136)
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by DimanAM** [comment]
Have you installed latest Android Support Repository?
![screen shot 2016-01-19 at 15 48 32](https://cloud.githubusercontent.com/assets/13101544/12415208/33e9f85a-bebc-11e5-9d90-4608365b5561.png)

**Comment by mayurloved** [comment]
Yes 
I have installed it.

**Comment by DimanAM** [comment]
Try building 'dependencies' task in android project to see what versions of libraries you are actually using:
```
$ ./gradlew dependencies

...
_releaseApk - ## Internal use, do not manually configure ##
+--- com.google.android.gms:play-services-gcm:+ -> 8.4.0
|    +--- com.google.android.gms:play-services-base:8.4.0
|    |    \--- com.google.android.gms:play-services-basement:8.4.0
|    |         \--- com.android.support:support-v4:23.0.0 -> 23.1.1
|    |              \--- com.android.support:support-annotations:23.1.1
|    \--- com.google.android.gms:play-services-measurement:8.4.0
|         \--- com.google.android.gms:play-services-basement:8.4.0 (*)
+--- com.android.support:support-v4:+ -> 23.1.1 (*)
\--- project :CordovaLib
```

**Comment by mayurloved** [comment]
You mean in Android Studio i have to run this command or in Terminal ?

On Wed, Jan 20, 2016 at 11:40 AM, DimanAM <notifications@github.com> wrote:

> Try building 'dependencies' task in android project to see what versions
> of libraries you are actually using:
>
> $ ./gradlew dependencies
>
> ...
> _releaseApk - ## Internal use, do not manually configure ##
> +--- com.google.android.gms:play-services-gcm:+ -> 8.4.0
> |    +--- com.google.android.gms:play-services-base:8.4.0
> |    |    \--- com.google.android.gms:play-services-basement:8.4.0
> |    |         \--- com.android.support:support-v4:23.0.0 -> 23.1.1
> |    |              \--- com.android.support:support-annotations:23.1.1
> |    \--- com.google.android.gms:play-services-measurement:8.4.0
> |         \--- com.google.android.gms:play-services-basement:8.4.0 (*)
> +--- com.android.support:support-v4:+ -> 23.1.1 (*)
> \--- project :CordovaLib
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/issues/153#issuecomment-173106230>
> .
>



-- 
Regards,

[image: Excellent Web World] <http://www.excellentwebworld.com>

Mayur Panchal  / CEO,Co-Founder
admin@excellentwebworld.com / +91-997-497-4355

Skype : pmayur355

Excellent Web World

http://www.excellentwebworld.com


[image: Facebook] <https://www.facebook.com/ExcellentWebWorld> [image:
Twitter] <https://twitter.com/excellentweb> [image: Google Plus]
<https://plus.google.com/+Excellentwebworld>

**Comment by shaders** [comment]
Yes, run this command in terminal.

**Comment by mayurloved** [comment]
Hello,

I tried but it give below error.

![screen shot 2016-01-21 at 2 23 23 pm](https://cloud.githubusercontent.com/assets/3961325/12475683/a584ca00-c04a-11e5-8ac5-1e9fc8c324b2.png)

**Comment by shaders** [comment]
This error:
java.lang.NoSuchMethodError: android.support.v4.content.ContextCompat.getNoBackupFilesDir

Means that the project is linking to the old Android Support Library jar file which does not have this method. 
There are two possible reasons for this:
1. Some other plugin is using old Android Support Library
2. Your Android SDK does not have the latest Android Support Library and Android Support Repository installed.

Do you use any other plugins for phonegap project which might have android-support-v4.jar in it?

**Comment by mayurloved** [comment]
Hello,

Final I found the issue.

I was using Facebook Plugin and that was using old jar.
So i have remove that plugin and use new facebook plugin(https://github.com/jeduan/cordova-plugin-facebook4).

Hope that help someone else.

and all working fine.

Thanks for support.

**Comment by shaders** [comment]
:+1:

**Comment by RishabhJain1603** [comment]
HI,
I am also getting the same error. My code is seems to be working fine in gradle environment but when I am trying to migrate it over to Maven everything compiles successfully but at the run time getting below error:

FATAL EXCEPTION: IntentService[RegIntentService]
                                                              java.lang.NoSuchMethodError: android.support.v4.content.ContextCompat.getNoBackupFilesDir
                                                                  at com.google.android.gms.iid.zzd.zzeb(Unknown Source)
                                                                  at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                                  at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                                  at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
                                                                  at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
                                                                  at com.att.safe.gcm.RegistrationIntentService.onHandleIntent(RegistrationIntentService.java:55)
                                                                  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                  at android.os.HandlerThread.run(HandlerThread.java:60)

Content of my POM.xml file is as below:
<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<platform.version> 4.1.1.4
			</platform.version>
		<android.plugin.version>3.6.0</android.plugin.version>
	</properties>

	
	<dependencies>
		<dependency>
			<groupId>com.google.android</groupId>
			<artifactId>android</artifactId>
			<version>${platform.version}</version>
			<scope>provided</scope>
		</dependency>




		<dependency>
			<groupId>com.android.support</groupId>
			<artifactId>support-v4</artifactId>
			<version>19.1.0</version>
		</dependency>
		<dependency>
			<groupId>google-play-services</groupId>
			<artifactId>google-play-services</artifactId>
			<version>1.0.0</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/libs/google-play-services.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>ATTSpeechKit</groupId>
			<artifactId>ATTSpeechKit</artifactId>
			<version>1.0.0</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/libs/ATTSpeechKit.jar</systemPath>
		</dependency>
		<dependency>
			<groupId>gson</groupId>
			<artifactId>gson</artifactId>
			<version>2.2.4</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/libs/gson-2.2.4.jar</systemPath>
		</dependency>

		<dependency>
			<groupId>android-logging-log4j</groupId>
			<artifactId>android-logging-log4j</artifactId>
			<version>1.0.3</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/libs/android-logging-log4j-1.0.3.jar</systemPath>
		</dependency>

		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.0.0</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/libs/log4j.jar</systemPath>
		</dependency>

		<dependency>
			<groupId>org.apache.felix.prefs</groupId>
			<artifactId>org.apache.felix.prefs</artifactId>
			<version>1.0.4</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/libs/org.apache.felix.prefs-1.0.4.jar</systemPath>
		</dependency>

		<dependency>
			<groupId>slf4j-api</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>2.0.99</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/libs/slf4j-api-2.0.99.jar</systemPath>
		</dependency>

		<dependency>
			<groupId>slf4j-log4j12</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.5.11</version>
			<scope>system</scope>
			<systemPath>${project.basedir}/libs/slf4j-log4j12-1.5.11.jar</systemPath>
		</dependency>

Thanks in advance. How did you come to know that if any of other jars is using the previous support version. If this is the case for my problem, then it should not run on Gradle too but seems like it is working fine on Gradle Environment.

Thank you. Please help me to resolve the same error.

**Comment by DimanAM** [comment]
>>        <artifactId>support-v4</artifactId>
>>        <version>19.1.0</version>
I think you should use latest support-v4 version
