### ISSUE TITLE
Error when adding plugin on mac

### ISSUE THREAD

**Issue by jQrgen** [Pushwoosh/pushwoosh-phonegap-plugin#163]
Output:
```
Stians-iMac:flare Stian$ ionic plugin add https://github.com/Pushwoosh/pushwoosh-phonegap-plugin --save
Fetching plugin "https://github.com/Pushwoosh/pushwoosh-phonegap-plugin" via git clone
Repository "https://github.com/Pushwoosh/pushwoosh-phonegap-plugin" checked out to git ref "master".
Installing "com.pushwoosh.plugins.pushwoosh" for ios
Saved plugin info for "com.pushwoosh.plugins.pushwoosh" to config.xml
Saving plugin to package.json file
Error happened [TypeError: Cannot convert undefined or null to object]
TypeError: Cannot convert undefined or null to object
    at Function.keys (native)
    at Object.getPluginFromFetchJsonByLocator (/Users/Stian/.nvm/versions/node/v4.2.3/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:744:26)
    at Object.savePlugin (/Users/Stian/.nvm/versions/node/v4.2.3/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:673:36)
    at /Users/Stian/.nvm/versions/node/v4.2.3/lib/node_modules/ionic/lib/ionic/cordova.js:185:22
    at _fulfilled (/Users/Stian/.nvm/versions/node/v4.2.3/lib/node_modules/ionic/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/Stian/.nvm/versions/node/v4.2.3/lib/node_modules/ionic/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/Stian/.nvm/versions/node/v4.2.3/lib/node_modules/ionic/node_modules/q/q.js:749:13)
    at /Users/Stian/.nvm/versions/node/v4.2.3/lib/node_modules/ionic/node_modules/q/q.js:557:44
    at flush (/Users/Stian/.nvm/versions/node/v4.2.3/lib/node_modules/ionic/node_modules/q/q.js:108:17)
    at doNTCallback0 (node.js:419:9)
```

Stians-iMac:flare Stian$ ionic info

Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Version: 1.2.1-nightly-1867
Ionic CLI Version: 2.0.0-beta.19
Ionic App Lib Version: 2.0.0-beta.9
ios-deploy version: 1.8.5
ios-sim version: 5.0.6
OS: Mac OS X El Capitan
Node Version: v4.2.3
Xcode version: Xcode 7.2.1 Build version 7C1002

**Comment by jQrgen** [comment]
ionic plugin add pushwoosh-cordova-plugin --save
worked an made no error.
