### ISSUE TITLE
Fatal Exception on launching application

### ISSUE THREAD

**Issue by jdflaugergues** [Pushwoosh/pushwoosh-phonegap-plugin#192]
Hi, 

Using the last version 5.1.3 of pushwoosh cordova plugin, I've the following error on calling registerDevice function.

```07-08 10:38:48.110 1660-3611/? E/AndroidRuntime: FATAL EXCEPTION: IntentService[GCMRegistrationService]
                                                 java.lang.IncompatibleClassChangeError: android.support.v4.content.ContextCompat
                                                     at com.google.android.gms.iid.zzd.zzeC(Unknown Source)
                                                     at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                     at com.google.android.gms.iid.zzd.<init>(Unknown Source)
                                                     at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
                                                     at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
                                                     at com.pushwoosh.GCMRegistrationService.register(Unknown Source)
                                                     at com.pushwoosh.GCMRegistrationService.onHandleIntent(Unknown Source)
                                                     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
                                                     at android.os.Handler.dispatchMessage(Handler.java:107)
                                                     at android.os.Looper.loop(Looper.java:194)
                                                     at android.os.HandlerThread.run(HandlerThread.java:60)
07-08 10:38:48.266 561-580/? E/AppErrorDialog: Failed to get ILowStorageHandle instance
07-08 10:38:48.853 561-580/? E/NotificationService: Ignoring notification with icon==0: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x62 kind=[null])```

**Comment by DimanAM** [comment]
You have inconsistant Android Support v4 and Google Play Services versions. Try updating Android SDK.

**Comment by jdflaugergues** [comment]
It works

Thanks a lot.
