### ISSUE TITLE
Error  - ionic state save fails after installing plugin

### ISSUE THREAD

**Issue by OSAlberto** [Pushwoosh/pushwoosh-phonegap-plugin#196]
the plugin installs without error:

`ionic plugin add pushwoosh-cordova-plugin --save
`
it seems to work but i can't save the state in ionic....

```
alberto$ ionic state save
Saving your Ionic app state of platforms and plugins
Saved platform
There was an error saving your current Ionic setup
 TypeError: Cannot read property 'LOG_LEVEL' of null
    at /usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:259:33
    at Array.forEach (native)
    at Object.saveExistingPlugins (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:251:22)
    at Object.saveState (/usr/local/lib/node_modules/ionic/node_modules/ionic-app-lib/lib/state.js:72:11)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/ionic/state.js:82:13)
    at Object.run (/usr/local/lib/node_modules/ionic/lib/cli.js:95:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/ionic/bin/ionic:9:10)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)

```

my ionic info

```

Your system information:

Cordova CLI: 6.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Framework Version: 1.3.1
Ionic CLI Version: 1.7.16
Ionic App Lib Version: 0.7.3
ios-deploy version: 1.8.6 
ios-sim version: 5.0.3 
OS: Mac OS X Yosemite
Node Version: v5.4.1
Xcode version: Xcode 7.2.1 Build version 7C1002 
```

**Comment by DimanAM** [comment]
It's Ionic bug. It tries to read plugin variables from `fetch.json` where they are not presented.
As a workaround you can copy/paste variables manually from `android.json`/`ios.json` (`installed_plugins.pushwoosh-cordova-plugin` object) to fetch.json (`pushwoosh-cordova-plugin.variables` object) in `plugins` directory.

**Comment by OSAlberto** [comment]
Thanks! This solve the problem.

**Comment by endriazizi** [comment]
@DimanAM @OSAlberto can someone explain better please?
Is not too clear how to solve it:

`There was an error saving your current Ionic setup                                                                                                                
 TypeError: Cannot read property 'LOG_LEVEL' of null                                                                                                              
    at C:\Users\endriazizi\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\state.js:259:34                                                  
    at Array.forEach (native)                                                                                                                                     
    at Object.saveExistingPlugins (C:\Users\endriazizi\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\state.js:250:24)                     
    at Object.saveState (C:\Users\endriazizi\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\state.js:73:11)                                
    at Object.run (C:\Users\endriazizi\AppData\Roaming\npm\node_modules\ionic\lib\ionic\state.js:55:11)                                                           
    at Promise.apply (C:\Users\endriazizi\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:1078:26)                                                     
    at Promise.promise.promiseDispatch (C:\Users\endriazizi\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:741:41)                                    
    at C:\Users\endriazizi\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:1304:14                                                                     
    at flush (C:\Users\endriazizi\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:108:17)                                                              
    at _combinedTickCallback (internal/process/next_tick.js:67:7)`

**Comment by elloboblanco** [comment]
@endriazizi the problem is the installation itself, you need to provide the variables to ionic cli like this 

    ionic plugin add pushwoosh-cordova-plugin --variable LOG_LEVEL=DEBUG --variable IOS_FOREGROUND_ALERT_TYPE=NONE --variable ANDROID_FOREGROUND_PUSH=false

which will add the variables to the correct sections in fetch.json then a subsequent `ionic state save` will work.
