### ISSUE TITLE
PushWoosh registerUser response error

### ISSUE THREAD

**Issue by Moataz512** [Pushwoosh/pushwoosh-phonegap-plugin#215]
hey 
i tried to install pushwoosh on my native app (cordova)
its show me response is ok but i can't receive notifications , and lately started to get error .. 

the log is ..

D/Pushwoosh: [CordovaPlugin] Plugin Method Called: onDeviceReady
D/Pushwoosh: [CordovaPlugin] broadcastPush = false
E/Pushwoosh: Unrecognized log level: undefined
I/Pushwoosh: Log level: NOISE
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/net.sonaranew.app/shared_prefs/com.pushwoosh.registration.xml.bak
V/Pushwoosh: [RegistrationPrefs] Saving regId on app version 10003
I/Pushwoosh: [PushManager] App ID: 40425-3F768
I/Pushwoosh: [PushManager] Project ID: 246513651128
I/Pushwoosh: [PushManager] This is android device
D/Pushwoosh: [RequestManager] Try To send: registerUser
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/net.sonaranew.app/shared_prefs/com.pushwoosh.pushnotifications.xml.bak
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
D/Pushwoosh: [RequestManager] Try To send: getInApps
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
V/Pushwoosh: [PushRegistrarGCM] number of receivers for net.sonaranew.app: 4
V/Pushwoosh: [PushRegistrarGCM] Found 1 receivers for action com.google.android.c2dm.intent.RECEIVE
W/PluginManager: THREAD WARNING: exec() call to PushNotification.onDeviceReady blocked the main thread for 65ms. Plugin should use CordovaInterface.getThreadPool().
D/Pushwoosh: [CordovaPlugin] Plugin Method Called: registerDevice
D/Pushwoosh: [RequestManager] Try To send: applicationOpen
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
V/Pushwoosh: [GCMRegistrationService] Intent action = com.pushwoosh.gcm.intent.REGISTER
I/chromium: [INFO:CONSOLE(124)] "Uncaught TypeError: Cannot read property 'querySelector' of null", source: file:///android_asset/www/js/index.js (124)
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/net.sonaranew.app/shared_prefs/com.google.android.gms.appid.xml.bak
W/InstanceID/Rpc: Found 10020
D/Pushwoosh: [GCMRegistrationService] GCM registration success
V/Pushwoosh: [RegistrationPrefs] Saving regId on app version 10003
W/Pushwoosh: [DeviceRegistrar] Registering for pushes
D/ViewRootImpl: ViewPostImeInputStage processPointer 0
D/ViewRootImpl: ViewPostImeInputStage processPointer 1
D/JsMessageQueue: Set native->JS mode to null
W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 14939
D/JsMessageQueue: Set native->JS mode to OnlineEventsBridgeMode
W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 14939
D/ViewRootImpl: #1 mView = com.android.internal.policy.PhoneWindow$DecorView{78d78f9 V.E...... R.....I. 0,0-0,0}
D/mali_winsys: EGLint new_window_surface(egl_winsys_display_, void_, EGLSurface, EGLConfig, egl_winsys_surface*_, egl_color_buffer_format_, EGLBoolean) returns 0x3000,  [1592x1011]-format:1
W/DisplayListCanvas: DisplayListCanvas is started on unbinded RenderNode (without mOwningView)
D/libGLESv1: DTS_GLAPI : DTS is not allowed for Package : net.sonaranew.app
D/ViewRootImpl: MSG_RESIZED_REPORT: ci=Rect(0, 0 - 0, 0) vi=Rect(0, 0 - 0, 0) or=1
D/ViewRootImpl: ViewPostImeInputStage processPointer 0
D/ViewRootImpl: ViewPostImeInputStage processPointer 1
D/OpenGLRenderer: endAllActiveAnimators on 0x7f208b3800 (RippleDrawable) with handle 0x7f208bfc00
D/ViewRootImpl: #3 mView = null
I/chromium: [INFO:CONSOLE(104)] "Uncaught TypeError: Cannot read property 'createBannerView' of undefined", source: file:///android_asset/www/main.html (104)
I/chromium: [INFO:CONSOLE(1030)] "'webkitCancelRequestAnimationFrame' is vendor-specific. Please use the standard 'cancelAnimationFrame' instead.", source: file:///android_asset/www/js/iScroll.js (1030)
E/ViewRootImpl: sendUserActionEvent() mView == null
I/Pushwoosh: [RequestManager] 
             x
             |     Pushwoosh request:
             | Url: https://cp.pushwoosh.com/json/1.3/registerUser
             | Payload: {"request":{"v":"4.6.1","device_type":3,"application":"40425-3F768","hwid":"16022b39b8a2f866","userId":"16022b39b8a2f866"}}
             | Response: {"status_code": 200, "status_message": "OK","response":null}
             x
D/Pushwoosh: [RequestManager] registerUser response success
E/Pushwoosh: [RequestManager] ERROR: https://cp.pushwoosh.com/json/1.3/getInApps. Response = null
             java.io.FileNotFoundException: https://cp.pushwoosh.com/json/1.3/getInApps
                 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:242)
                 at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                 at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
                 at com.pushwoosh.internal.b.k.a(Unknown Source)
                 at com.pushwoosh.internal.b.k.a(Unknown Source)
                 at com.pushwoosh.inapp.InAppRetrieverService.onHandleIntent(Unknown Source)
                 at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                 at android.os.Handler.dispatchMessage(Handler.java:102)
                 at android.os.Looper.loop(Looper.java:158)
                 at android.os.HandlerThread.run(HandlerThread.java:61)
V/ActivityThread: updateVisibility : ActivityRecord{2d07802 token=android.os.BinderProxy@4a578a5 {net.sonaranew.app/net.sonaranew.app.MainActivity}} show : false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
E/Pushwoosh: [RequestManager] ERROR: https://cp.pushwoosh.com/json/1.3/applicationOpen. Response = null
             java.io.FileNotFoundException: https://cp.pushwoosh.com/json/1.3/applicationOpen
                 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:242)
                 at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                 at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
                 at com.pushwoosh.internal.b.k.a(Unknown Source)
                 at com.pushwoosh.internal.b.k.a(Unknown Source)
                 at com.pushwoosh.internal.b.k$1.run(Unknown Source)
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
D/Pushwoosh: [RequestManager] Try To send: registerDevice
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
E/Pushwoosh: [RequestManager] ERROR: https://cp.pushwoosh.com/json/1.3/registerDevice. Response = null
             java.io.FileNotFoundException: https://cp.pushwoosh.com/json/1.3/registerDevice
                 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:242)
                 at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                 at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
                 at com.pushwoosh.internal.b.k.a(Unknown Source)
                 at com.pushwoosh.internal.b.k.a(Unknown Source)
                 at com.pushwoosh.internal.b.k$1.run(Unknown Source)
E/Pushwoosh: [DeviceRegistrar] Registration error https://cp.pushwoosh.com/json/1.3/registerDevice
             java.io.FileNotFoundException: https://cp.pushwoosh.com/json/1.3/registerDevice
                 at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:242)
                 at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                 at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
                 at com.pushwoosh.internal.b.k.a(Unknown Source)
                 at com.pushwoosh.internal.b.k.a(Unknown Source)
                 at com.pushwoosh.internal.b.k$1.run(Unknown Source)

**Comment by viridanti** [comment]
Hi,

Does the issue with receiving notifications still persist? 

Regarding errors in the log, it seems that the device could not connect to Pushwoosh server for some reason. Please check whether there is something that could restrict the connection.
