### ISSUE TITLE
App crash Andoid only

### ISSUE THREAD

**Issue by sparh** [Pushwoosh/pushwoosh-phonegap-plugin#267]
Hi
I am using Phonegap Build and version 7.0.6  of this plugin (since 7.0.7 is not working with Phonegap Build
Yesterday I have succefully pubish my app and everything was working.
Today I have updated my app and it is now impossible to load it on Android (IOS work as expected)
I did not change the pushwoosh code.
If I remove the pushwoosh plugin app is working

Here are the report from Google play developper console : 
**Samsung Galaxy S7 Edge (hero2lte), 4096MB RAM, Android 7.0**
java.lang.RuntimeException: 
  at android.os.AsyncTask$3.done (AsyncTask.java:318)
  at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:354)
  at java.util.concurrent.FutureTask.setException (FutureTask.java:223)
  at java.util.concurrent.FutureTask.run (FutureTask.java:242)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
  at java.lang.Thread.run (Thread.java:762)
Caused by: java.lang.NoSuchMethodError: 
  at com.google.android.gms.iid.zzh.<init> (Unknown Source)
  at com.google.android.gms.iid.zzh.<init> (Unknown Source)
  at com.google.android.gms.iid.InstanceID.getInstance (Unknown Source)
  at com.google.android.gms.iid.InstanceID.getInstance (Unknown Source)
  at com.pushwoosh.internal.registrar.a$a.d (Unknown Source)
  at com.pushwoosh.internal.registrar.a$a.a (Unknown Source)
  at com.pushwoosh.internal.registrar.b.run (Unknown Source)
  at com.pushwoosh.PushwooshService.onHandleWork (Unknown Source)
  at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:391)
  at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:382)
  at android.os.AsyncTask$2.call (AsyncTask.java:304)
  at java.util.concurrent.FutureTask.run (FutureTask.java:237)

**Galaxy Grand Prime (fortuna3g) Android 4.4**
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NoSuchMethodError: com.google.android.gms.common.util.zzt.getNoBackupFilesDir
	at com.google.android.gms.iid.zzh.<init>(Unknown Source)
	at com.google.android.gms.iid.zzh.<init>(Unknown Source)
	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
	at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
	at com.pushwoosh.internal.registrar.a$a.d(Unknown Source)
	at com.pushwoosh.internal.registrar.a$a.a(Unknown Source)
	at com.pushwoosh.internal.registrar.b.run(Unknown Source)
	at com.pushwoosh.PushwooshService.onHandleWork(Unknown Source)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
	at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

**Comment by wfhm** [comment]
Hi,

I could not reproduce the issue with [the very basic sample](https://github.com/Pushwoosh/phonegap-build-sample-app). Could you please elaborate? 

> Yesterday I have succefully pubish my app and everything was working.
Today I have updated my app and it is now impossible to load it on Android (IOS work as expected)
I did not change the pushwoosh code.

Were you using the same plugin version (7.0.6) both yesterday and today? When updating your code, did you add any 3rd-party plugins which use Google Play Services libs? Which versions are used?

**Comment by sparh** [comment]
Hi
 I did a new build today and now it is working!!!
