### ISSUE TITLE
APP crashes on Initialization

### ISSUE THREAD

**Issue by danilohk** [Pushwoosh/pushwoosh-phonegap-plugin#275]
I am having problems with version 7.2.2 of the plugin, it crashes and has the following error:

FATAL EXCEPTION: main
                                                 Process: com.escola.EducaOnline, PID: 6893
                                                 java.lang.RuntimeException: Unable to get provider com.pushwoosh.PushwooshInitProvider: java.lang.IllegalStateException: You must include the following maven repository URL in project build.gradle:
                                                  allprojects {
                                                     repositories {
                                                         jcenter ()
                                                         maven {
                                                             url "https://maven.google.com"
                                                          }
                                                     } 
                                                 }
                                                 Also all support libraries must be at least v26.0.1. For more info look at https://github.com/Pushwoosh/pushwoosh-android-sdk/blob/master/README.md
                                                 
                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:5897)
                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:5486)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5425)
                                                     at android.app.ActivityThread.-wrap2(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1558)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6165)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
                                                  Caused by: java.lang.IllegalStateException: You must include the following maven repository URL in project build.gradle:
                                                  allprojects {
                                                     repositories {
                                                         jcenter ()
                                                         maven {
                                                             url "https://maven.google.com"
                                                          }
                                                     } 
                                                 }
                                                 Also all support libraries must be at least v26.0.1. For more info look at https://github.com/Pushwoosh/pushwoosh-android-sdk/blob/master/README.md
                                                 
                                                     at com.pushwoosh.internal.checker.c.check(Unknown Source)
                                                     at com.pushwoosh.internal.checker.a.b(Unknown Source)
                                                     at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source)
                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
                                                     at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:5894)
                                                     	... 10 more

**Comment by wfhm** [comment]
Hi,

As the exception message says, all support libraries must be at least v26.0.1. Could you please confirm that you have at least 26.0.1 version of android-support libraries added to your Android SDK Manager?

**Comment by wfhm** [comment]
@danilohk any news on this one?

**Comment by ivanicin** [comment]
I can confirm that the error appears with v27 of the support library...
