### ISSUE TITLE
I have crash error

### ISSUE THREAD

**Issue by webquali** [Pushwoosh/pushwoosh-phonegap-plugin#307]
2019-02-01 17:42:27.638 13183-13386/com.dopios.driverapp E/AndroidRuntime: FATAL EXCEPTION: Firebase-PushFcmIntentService
    Process: com.dopios.driverapp, PID: 13183
    java.lang.AbstractMethodError: abstract method "void com.google.firebase.iid.zzb.zzd(android.content.Intent)"
        at com.google.firebase.iid.zzg.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:764)

**Comment by webquali** [comment]
App crash on start

**Comment by wfhm** [comment]
@webquali 

This error means there was a mixture of different Firebase modules versions included in your app. Please check your build.gradle scripts and make sure you use the same version for all Firebase libraries.
