### ISSUE TITLE
PhoneGap Build error with version 7.13.0

### ISSUE THREAD

**Issue by mleroi** [Pushwoosh/pushwoosh-phonegap-plugin#312]
Hi,
PhoneGap Build is failing building my app as soon as I include "pushwoosh-pgb-plugin".

Here's the related config.xml part:

```
<preference name="phonegap-version" value="cli-7.1.0" />
<platform name="android">
    <resource-file src="google-services.json" target="/google-services.json" />
</platform>
<plugin name="pushwoosh-pgb-plugin" spec="7.13.0" source="npm" />
```

And the error logs:

```
[...]
Parsing json file: /var/gimlet/tmp/47349419709520/3531472/google-services.json
:generateDebugResources
:mergeDebugResources
:processDebugManifest
:processDebugResources
:generateDebugSources
:incrementalDebugJavaCompilationSafeguard
:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
:compileDebugNdk UP-TO-DATE
:compileDebugSources
:mergeDebugShaders
:compileDebugShaders
:generateDebugAssets
:mergeDebugAssets
:transformClassesWithDexForDebugDex: Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
    UNEXPECTED TOP-LEVEL EXCEPTION:
    java.lang.RuntimeException: Exception parsing classes
    	at com.android.dx.command.dexer.Main.processClass(Main.java:775)
    	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:741)
    	at com.android.dx.command.dexer.Main.access$1200(Main.java:88)
    	at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1683)
    	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
    	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
    	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
    	at com.android.dx.command.dexer.Main.processOne(Main.java:695)
    	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:592)
    	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:321)
    	at com.android.dx.command.dexer.Main.run(Main.java:292)
    	at com.android.builder.internal.compiler.DexWrapper.run(DexWrapper.java:54)
    	at com.android.builder.core.DexByteCodeConverter.lambda$dexInProcess$0(DexByteCodeConverter.java:173)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)
    Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
    	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:476)
    	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
    	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
    	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
    	at com.android.dx.command.dexer.Main.parseClass(Main.java:787)
    	at com.android.dx.command.dexer.Main.access$1600(Main.java:88)
    	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1722)
    	at com.android.dx.command.dexer.Main.processClass(Main.java:773)
    	... 16 more
    
1 error; aborting
 FAILED
[...]
```

Do you know where this can come from?
Thanks!

**Comment by wfhm** [comment]
Hi @mleroi ,

Checking it.

**Comment by wfhm** [comment]
@mleroi 

It builds with the following setup:

```
<preference name="phonegap-version" value="cli-8.0.0" />
 <plugin name="pushwoosh-pgb-plugin" spec="7.13.0" source="npm" />
 <platform name="android">
 <resource-file src="google-services.json" target="app/google-services.json" />
 </platform>
```

Please try adding it to your config.xml and let us know about the results.

**Comment by wfhm** [comment]
Closed as outdated. The latest version of the plugin works just fine with Phonegap Build.
