### ISSUE TITLE
Cannot find build.gradle

### ISSUE THREAD

**Issue by shabrany** [Pushwoosh/pushwoosh-phonegap-plugin#322]
I try to add the pushwoosh plugin to an Ionic project, but it ends in a error

```
C:\Users\jorge.fernandez\Projects\**********>ionic cordova plugin add pushwoosh-cordova-plugin
> cordova.cmd plugin add pushwoosh-cordova-plugin
Installing "pushwoosh-cordova-plugin" for android
Error during processing of action! Attempting to revert...
Failed to install 'pushwoosh-cordova-plugin': CordovaError: Uh oh!
"C:\Users\jorge.fernandez\Projects\**********\plugins\pushwoosh-cordova-plugin\build.gradle" not found!
    at copyFile (C:\Users\jorge.fernandez\Projects\**********\platforms\android\cordova\lib\pluginHandlers.js:208:36)
    at copyNewFile (C:\Users\jorge.fernandez\Projects\**********\platforms\android\cordova\lib\pluginHandlers.js:236:5)
    at install (C:\Users\jorge.fernandez\Projects\**********\platforms\android\cordova\lib\pluginHandlers.js:80:17)
    at ActionStack.process (C:\Users\jorge.fernandez\Projects\**********\node_modules\cordova-common\src\ActionStack.js:56:25)
    at PluginManager.doOperation (C:\Users\jorge.fernandez\Projects\**********\node_modules\cordova-common\src\PluginManager.js:114:20)
    at PluginManager.addPlugin (C:\Users\jorge.fernandez\Projects\**********\node_modules\cordova-common\src\PluginManager.js:144:17)
    at C:\Users\jorge.fernandez\Projects\**********\platforms\android\cordova\Api.js:212:74
    at _fulfilled (C:\Users\jorge.fernandez\Projects\**********\node_modules\q\q.js:834:54)
    at C:\Users\jorge.fernandez\Projects\**********\node_modules\q\q.js:863:30
Uh oh!
"C:\Users\jorge.fernandez\Projects\**********\plugins\pushwoosh-cordova-plugin\build.gradle" not found!
    at Promise.promise.promiseDispatch (C:\Users\jorge.fernandez\Projects\**********\node_modules\q\q.js:796:13)
[ERROR] An error occurred while running subprocess cordova.

        cordova.cmd plugin add pushwoosh-cordova-plugin exited with exit code 1.
```

Ionic info

```
Ionic:

   Ionic CLI                     : 5.2.6 (C:\Users\jorge.fernandez\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.8
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.3.8
   @ionic/angular-toolkit        : 1.4.1

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0
   Cordova Plugins   : cordova-plugin-ionic 5.4.0, cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.0, (and 13 other plugins)

Utility:

   cordova-res : not installed
   native-run  : 0.2.8

System:

   Android SDK Tools : 26.1.1 (C:\Users\jorge.fernandez\AppData\Local\Android\Sdk)
   NodeJS            : v10.16.0 (C:\Program Files\nodejs\node.exe)
   npm               : 6.9.0
   OS                : Windows 10
```

**Comment by wfhm** [comment]
Hello @shabrany,

Please let me pull some time to investigate it.

**Comment by TimBosbec** [comment]
I have the same issue with phonegap build 

`Error - Plugin error (you probably need to remove plugin files from your app): Fetching plugin "pushwoosh-cordova-plugin@~7.18.0" via npm Installing "pushwoosh-cordova-plugin" at "7.18.0" for android Error during processing of action! Attempting to revert... Failed to install 'pushwoosh-cordova-plugin': CordovaError: Uh oh! "/var/gimlet/tmp/47214804103440/3681417/www_android/cordova/plugins/pushwoosh-cordova-plugin/build.gradle" not found! at copyFile `

**Comment by anibalsanchez** [comment]
Same issue here.

**Comment by anibalsanchez** [comment]
```
Subproject Path: app
"plugman-151 install --platform android --project /var/gimlet/tmp/47096636867560/2739082 --plugin pushwoosh-pgb-plugin@^7.18.0 --nohooks=. --var ANDROID_FOREGROUND_PUSH=true --var LOG_LEVEL=ERROR --var IOS_FOREGROUND_ALERT_TYPE=ALERT": Fetching plugin "pushwoosh-pgb-plugin@^7.18.0" via npm
Installing "pushwoosh-cordova-plugin" at "7.18.0" for android
Error during processing of action! Attempting to revert...
Failed to install 'pushwoosh-cordova-plugin': CordovaError: Uh oh!
"/var/gimlet/tmp/47096636867560/2739082/cordova/plugins/pushwoosh-cordova-plugin/build.gradle" not found!
    at copyFile (/var/gimlet/tmp/47096636867560/2739082/cordova/lib/pluginHandlers.js:208:36)
    at copyNewFile (/var/gimlet/tmp/47096636867560/2739082/cordova/lib/pluginHandlers.js:236:5)
    at install (/var/gimlet/tmp/47096636867560/2739082/cordova/lib/pluginHandlers.js:80:17)
    at ActionStack.process (/var/gimlet/tmp/47096636867560/2739082/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PluginManager.doOperation (/var/gimlet/tmp/47096636867560/2739082/cordova/node_modules/cordova-common/src/PluginManager.js:114:20)
    at PluginManager.addPlugin (/var/gimlet/tmp/47096636867560/2739082/cordova/node_modules/cordova-common/src/PluginManager.js:144:17)
    at /var/gimlet/tmp/47096636867560/2739082/cordova/Api.js:212:74
    at _fulfilled (/var/gimlet/tmp/47096636867560/2739082/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/var/gimlet/tmp/47096636867560/2739082/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/var/gimlet/tmp/47096636867560/2739082/cordova/node_modules/q/q.js:816:13)
Uh oh!
"/var/gimlet/tmp/47096636867560/2739082/cordova/plugins/pushwoosh-cordova-plugin/build.gradle" not found!
```

**Comment by wfhm** [comment]
@anibalsanchez @TimBosbec @shabrany,

Confirmed, working on the fix right now.

**Comment by wfhm** [comment]
@anibalsanchez @TimBosbec @shabrany,

Fixed with the latest release.

**Comment by Mapiac** [comment]
Hi wondering what the fix was? We just tried with latest and had a build failure 

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\user\mapiac\platforms\android\cordova-support-google-services\mapiac-build.gradle' line: 16  

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [class 'com.google.gms.googleservices.GoogleServicesPlugin']
   > Cannot add extension with name 'googleServices', as there is an extension already registered with that name.
